### ISSUE TITLE
Agregar un Wordle

### ISSUE THREAD

**Issue by adrgarcha** [adrgarcha/mariwano#24]
Hace tiempo vi un vídeo donde se creaba un comando para hacer un Wordle diario. Podría estar muy guapo y mejorar el uso del bot. Aquí dejo un enlace al vídeo en concreto: https://www.youtube.com/watch?v=-Xb1wICIL7E&pp=ygURd29yZGxlIGRpc2NvcmQganM%3D.

**Comment by davider0** [comment]
[wordle.js](https://github.com/adrgarcha/mariwano-bot/blob/porrazo/src/commands/fun/wordle.js)
