### ISSUE TITLE
Permitir notificaciones de más de una persona

### ISSUE THREAD

**Issue by adrgarcha** [adrgarcha/mariwano#28]
Actualmente, en el comando de notificaciones sólo se permiten las notificaciones de un canal, así que me gustaría que se pudiesen agregar varios canales al mismo tiempo.

**Comment by davider0** [comment]
[cambios propuestos](https://github.com/adrgarcha/mariwano-bot/compare/porrazo?expand=1#diff-0b38186ba3432c35acc1723df1e0655f8198c06d24a4a388f4b742203cc3515e)

**Comment by adrgarcha** [comment]
❌ Ya se pueden realizar notificaciones para mas de una persona y en distintos canales de Discord con las funcionalidades actuales.
