### ISSUE TITLE
Crear subcomandos para el comando /invertir

### ISSUE THREAD

**Issue by adrgarcha** [adrgarcha/mariwano#36]
El comando /invertir tiene varias opciones que no son fácilmente accesibles para los usuarios, o no se entiende del todo el funcionamiento del mismo.

Por lo tanto, se propone crear varios subcomandos que permitan diversificar /invertir, algunos ejemplos son los siguientes:
- /invertir-info: Permite conocer mejor como funciona el comando. O se podría mejorar la descripción.
- /invertir-claim: Para retirar el dinero que hayas invertido, hayas tenido beneficios o no.
- /invertir-user: Para invertir en un usuario.
- /invertir-channel: Para invertir en un canal.

También pueden surgir mas ideas de este comando, ya que tiene mucho futuro pero es necesario reforzar su funcionamiento.

Se puede tomar como ejemplo el comando /shop, el cual ya posee varios subcomandos para tareas especificas.

**Comment by davider0** [comment]
[https://github.com/adrgarcha/mariwano/blob/porrazo/src/commands/fun/invertir.ts](solucion)

**Comment by davider0** [comment]
[Link a la solucion](https://github.com/adrgarcha/mariwano/blob/main/src/commands/fun/invertir.ts)
