### ISSUE TITLE
Comando /invertir new desbalanceado por ganancias

### ISSUE THREAD

**Issue by davider0** [adrgarcha/mariwano#49]
El comando /invertir está balanceado según solo si se gana o pierde dinero, pero no de cuánto, en ese aspecto está todavía demasiado desequilibrado. 

Esto quiere decir que si hay muchas pérdidas, te dejará en banca rota mientras que si las ganancias son exageradas recibes un gazillion dollars

**Comment by adrgarcha** [comment]
Cambiar también el modelo de User para que en vez de Float utilize unicamente enteros para que se encuentre la validación a nivel de base de datos, hay un ejemplo en la documentación de Mongoose: https://mongoosejs.com/docs/schematypes.html

Comprobar que todos los comandos de economía no requieran de decimales.
